[project]
name = "scrape-tables"
version = "0.1.0"
description = "Scrape Tables of data from webpages"
readme = "README.md"
authors = [
    { name = "jbeattie5768", email = "jbeattie5768@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.2",  # >= 4.13 includes type stubs
    "requests>=2.32.5",
]

[project.scripts]
james-bond = "scrape_tables.examples.extract_bond_films:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "responses>=0.25.8", # Lib for mocking out requests lib for tests
    "types-requests>=2.32.4.20250913", # stub package
]

[tool.mypy]
# Make src the import root so modules are resolved as `scrape_tables.*`
mypy_path = ["src"]

# Explicit files to check (prevents accidental duplicate discovery)
files = ["src", "tests"]

ignore_missing_imports = false   # Display error for all missing imports
strict=true
