name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v6

      # https://github.com/marketplace/actions/setup-python
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      # https://github.com/marketplace/actions/astral-sh-setup-uv
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 'latest'
          # enable-cache: true

      # - name: Install Python via UV
      #   # Respects the proj pinned version
      #   run: uv python install

      # https://github.com/marketplace/actions/cache
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: .uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install dependencies with uv
        # Don't change uv.lock, all optional and dev dependencies
        run: uv sync --locked --all-extras --dev

      # Run Tests and Linters
      - name: Mypy
        run: uv run mypy --strict src tests

      - name: Deptry
        run: uv run deptry .

      - name: PyTest
        # run: uv run pytest -q --cov=src --cov-report=term-missing --cov-fail-under=100 tests
        run: uv run pytest -q

      - name: lint
        run: uv run ruff check . --line-length 120

      - name: format
        run: uv run ruff format --check . --line-length 120

      - name: Minimize uv cache
        # Reduce the size of the cache, optimised for CI
        run: uv cache prune --ci

  # Future: Add autoupdate-precommit here...
